### ISSUE TITLE
Config file format

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#17]
The INI file doesn't match any convention I recognise and is quite hard to read. There are better config handlers that do the parsing and loading for free. Here is an example TOML config file that I would be happy to do the work converting to, but I wanted to run the ideology by you first. 

```toml
title = "VMAT TBI configuration file"
EAS = 2021-06-11 #date only 
Site = "Saskatoon Cancer Center" 
Organization = "Saskatchewan Cancer Agency" 
#Paths are single quote'
Document_Path = '\\enterprise.stanfordmed.org\depts\RadiationTherapy\Public\Users\ESimiele\Research\VMAT_TBI\documentation\'
Linacs = ["LA16", "LA17"]
Energies = ["06X", "10X"]

[Plug-in]
    flash.default_flash_type = "Global"
    flash.default_flash_margin = 0.5
    flash.default_target_margin = 0.3
    calc.calculation_model = "AAA_15605"
    calc.optimization_model = "PO_15605"
    default_isos = 5
    #Default beams per iso from sup to inf, must have same or more entries then default isos
    default_beams_per_iso = [4, 3, 2, 2, 2, 0, 0]
    contour.field_overlap = true
    contour.field_overlap_margin = 1.0

Default_Sparing_Structures = [ 
    ["Lungs", "Mean Dose < Rx Dose", 0.3] ,
    ["Kidneys", "Mean Dose < Rx Dose", 0.0],
    ["Bowel", "Dmax ~ RX Dose", 0]
    #format ["name", "type", margin]
]

[Cases]
[Cases.Scleroderma]
    dose_per_fraction = 200
    number_of_fractions = 4
    constraints = [ #format ["Name", "type", dose, volume, priority]
        ["TS_PTV_VMAT", "Lower", 800.0, 100.0, 100]
        #continued in same format
    ]

[Cases.Myeloablative]
    dose_per_fraction = 200
    number_of_fractions = 6
    constraints = [[]]

[Cases.Non_Myeloablative]
    dose_per_fraction = 200
    number_of_fractions = 6
    constraints = [[]]
    sparing_structures = [
        [ "Ovaries","Mean Dose < Rx Dose",1.5 ]
    ]
```
